### ISSUE TITLE
Zamjenit hardkodirane vrijednosti sa pravim ENV varijablama

### ISSUE THREAD

**Issue by neektza** [floatingpointio/kroper#4]
https://github.com/floatingpointio/kroper/blob/master/s3.py#L4-L8

https://direnv.net/

**Comment by neektza** [comment]
Pobrisati SECRET_KEY iz git historya (repo je public, svatko ga može vidjeti).

Ovdje su upute kako to napraviti
https://help.github.com/articles/removing-sensitive-data-from-a-repository/

**Comment by pogy94** [comment]
Fixed: e125913ff167a70ae907e7d7882a13a0911317c8
